# Generated by Django 3.0.7 on 2020-06-23 05:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone No.')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MISS', 'Miss.'), ('MS', 'Ms.'), ('MRS', 'Mrs.'), ('DR', 'Dr.')], default='MR', max_length=10, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
